TITLE TEMPLATE
INCLUDE Irvine32.inc

.data
array word 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
msg1 byte "Mean :",0
msg2 byte "Variance:",0



.code
mean proc

PUSH EBP
MOV EBP, ESP
PUSH EDI ; APODESMEBW GIA NA TON XRHSIMOPOIHSV EGW
PUSH ESI 
PUSH EAX
PUSH ECX

MOV EDI, [EBP+8] ; EXV PAREI TWRA TO OFFSET ARRAY
MOV ESI, [EBP+12] ; EXV PAREI TWRA TO SIZE TOY ARRAY


;KSEKINAW THN FOR 
MOV ECX, 0 ; COUNTER
MOV EAX, 0 ; MEAN

JMP condition ; CHECKARISMA SYNTHIKHS GIA THN PRWTH FORA

lp:
ADD AX, [EDI +  2* ECX]
INC ECX ; AUKSISH KATA 1

condition: 
CMP ESI, ECX
JG lp 
; TELOS FOR

MOVZX EAX, AX
CDQ
DIV ESI

MOV EDI, [EBP + 16]
MOV [EDI], EAX

POP ECX
POP EAX
POP ESI
POP EDI
MOV ESP, EBP
POP EBP
ret 12 ; 3 pragmata epistrefw me 4 bytes to kathe ena ara epistrefw 12 bytes 
mean endp

variance proc

PUSH EBP
MOV EBP, ESP
PUSH EDI
PUSH EBX
PUSH ECX
PUSH ESI
PUSH EAX

MOV EDI, [EBP + 8] ; PAIRNW TO OFFSET POY ESTEILA
MOV EBX, [EBP+12] ; PAIRNW TO SIZE TOY PINAKA POY ESTEILA
; MOV ECX, [EBP+16]; PAIRNV THN TIMH THS PRWTHS METABLHTHS
;MOV EAX,[EBP+20] ;PAIRNV THN TIMH THS DEYTERHS METABLHTHS

MOV ECX,0 ; DHMIOURGIA COUNTER KAI ARXIKOPOIHSH ME 0
MOV EAX, 0 ; DHMIOYRGIA DIFF KAI ARXIKOPOIHSH ME 0
MOV ESI,0 ; DHMIOYRGIA VARIANCE KAI ARXIKOPOIHSH ME 0

JMP condition ; CHECKARISMA SYNTHIKHS GIA THN PRWTH FORA

lp:
MOV AX, [EDI + ECX *2] ; EPI 2 GIATI EXW WORD ARA 16BIT ARA 2 TWN 8 BITS ARA 2 TWN ENOS(1) BYTE
SUB AX, [EBP+16] ; AFAIRW APO TON SI TO MEAN (PROTELEYTAIO PRAGMA POY ESTEILA)
MUL AX ; YPOLOGIZW THN DYNAMH TOY DYO STO DIFF
ADD ESI, EAX ; PROSUETW STO VARIANCE TO DIFF KAI KANW TYPECAST WSTE TO 16BIT NA GINEI 32BIT KAIOLA KALA

INC ECX; AUKSHSH COUNTER KATA 1

condition:
CMP ECX , EBX
JL lp


MOV EAX, ESI
CDQ
DIV EBX

MOV ECX,0 ; KATHARISMOS ECX
MOV ECX, [EBP+20] ; PAIRNV TO TELAYTAIO PRAGMA POY STALTHIKE
MOV [ECX], EAX ; PAIRNEI THN TIMH TOY EAX 


POP EAX
POP ESI
POP ECX
POP EBX
POP EDI
MOV ESP, EBP
POP EBP

ret 16 ; 4 pragmata epistrefw me 4 bytes to kathe ena ara epistrefw 16 bytes 
variance endp

main proc

PUSH EBP
MOV EBP, ESP
SUB ESP, 8 ; ANEBA 2 KELIA
MOV [EBP -4], DWORD PTR 0 ; dhlwsh topikhs metablhths 1
MOV [EBP -8], DWORD PTR 0 ; dhlwsh topikhs metablhths 2


; MEAN (FTIAXNW TO TI UA STEILW)
LEA  EDI , [EBP - 4]; METAFERW THN DIEYUYNSH MNHMHS THS PRWTHS METABLHTHS STON KATAXWRHTH EDI
PUSH EDI
PUSH LENGTHOF array ; MHKOS PINAKA
PUSH OFFSET array ; O PINAKAS SAN DEIKTHS (DIEUTHISNH MNHMHS TOY PINAKA)
call mean ; kalw synarthsh

MOV EDX, OFFSET msg1
call WriteString
MOV EAX, [EBP-4]
call WriteInt
call Crlf

; VARIANCE
LEA EDI ,[EBP-8] ;METAFERW THN DIEYUYNSH MNHMHS THS DEYTERHD METABLHTHS STON KATAXWRHTH EDI
PUSH EDI
PUSH [EBP-4] ; PAIRNW THN TIMH THS PRWTHS METABLHTHS
PUSH LENGTHOF array ; MHKOS PINAKA
PUSH OFFSET array ; O PINAKAS SAN DEIKTHS (DIEUTHISNH MNHMHS TOY PINAKA)
call variance ; kalw synarthsh

MOV EDX, OFFSET msg2
call WriteString
MOV EAX, [EBP-8]
call WriteInt
call Crlf



exit
main endp
END main